apiVersion: apps/v1
kind: Deployment
metadata:
  name: internet-deployment
  labels:
    app: internet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internet
  template:
    metadata:
      labels:
        app: internet
    spec:
      containers:
        - name: internet
          image: ursuclaudia/internet
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: awbd-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: awbd-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: awbd-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: internet-service
spec:
  selector:
    app: internet
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080